### ISSUE TITLE
Important file

### ISSUE THREAD

**Issue by Milan-rawat** [aksh-22/stock-backend#1]
<h2>Issue</h2>
You have uploaded config.env file, it should be ignored, It contains important information like your  MongoDB URL and password.

<h2>Solution</h2>
Instead of uploading config.env you can upload another file named as 'config.txt' which contains environmental variable name without your original value, by doing this user can can easily understand what variables are used in the application.

**Comment by aksh-22** [comment]
thanks millan for noticing it , and yeah we shouldn't upload our credentials at first place not even with config.txt and here config.env was uploaded on purpose for specific reason now it is not needed so would delete it.

**Comment by Milan-rawat** [comment]
No, config.txt only contains the variable name not it's value, like

**config.txt**
```
DATABAS_URL=<Replace-with-your-database-URL>
PASSWORD=<Replace-with-your-database-password>
```

**Comment by aksh-22** [comment]
good point , will make sure next time.
